# Generated by Django 4.2 on 2023-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='symbol',
        ),
        migrations.AddField(
            model_name='method',
            name='buy_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='sell_rate',
            field=models.FloatField(null=True),
        ),
    ]
