# Generated by Django 4.2 on 2023-05-24 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('currency', '0002_currency_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('wtd', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
                ('from_curr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='currency.currency')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_method', to='payment.method')),
                ('to_curr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='currency.currency')),
            ],
        ),
    ]
