# Generated by Django 4.2 on 2023-05-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_curr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_curr',
        ),
    ]
