# Generated by Django 4.2 on 2023-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_from_curr_remove_order_to_curr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
